// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'PASTE_YOUR_WEB_API_KEY_HERE',
    appId: 'PASTE_YOUR_WEB_APP_ID_HERE',
    messagingSenderId: 'PASTE_YOUR_WEB_MESSAGING_SENDER_ID_HERE',
    projectId: 'your-nanhenest-project-id',
    authDomain: 'your-nanhenest-project-id.firebaseapp.com',
    databaseURL: 'https://your-nanhenest-project-id.firebaseio.com',
    storageBucket: 'your-nanhenest-project-id.appspot.com',
    measurementId: 'PASTE_YOUR_WEB_MEASUREMENT_ID_HERE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'PASTE_YOUR_ANDROID_API_KEY_HERE',
    appId: 'PASTE_YOUR_ANDROID_APP_ID_HERE',
    messagingSenderId: 'PASTE_YOUR_ANDROID_MESSAGING_SENDER_ID_HERE',
    projectId: 'your-nanhenest-project-id',
    storageBucket: 'your-nanhenest-project-id.appspot.com',
  );
}
